# Generated by Django 5.2.11 on 2026-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='flashcards',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tables_figures',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
